events {
    worker_connections 1024;
}
 
http {
    # Timeouts largos para SignalR (WebSockets de Blazor Server)
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
 
    # Upstreams: nombre → contenedor:puerto
    upstream shell          { server shell:8080; }
    upstream mfe_inicio     { server mfe-inicio:8081; }
    upstream mfe_portafolio { server mfe-portafolio:8082; }
    upstream mfe_siniestros { server mfe-siniestros:8083; }
 
    server {
        listen 80;
 
        # Headers necesarios para WebSockets (SignalR)
        proxy_http_version 1.1;
        proxy_set_header Upgrade        $http_upgrade;
        proxy_set_header Connection     "upgrade";
        proxy_set_header Host           $host;
        proxy_set_header X-Real-IP      $remote_addr;
        proxy_cache_bypass              $http_upgrade;
 
        # Shell principal
        location / {
            proxy_pass http://shell;
        }
 
        # MFE Inicio
        location /mfe-inicio/ {
            proxy_pass http://mfe_inicio/;
        }
 
        # MFE Portafolio
        location /mfe-portafolio/ {
            proxy_pass http://mfe_portafolio/;
        }
 
        # MFE Siniestros
        location /mfe-siniestros/ {
            proxy_pass http://mfe_siniestros/;
        }
    }
}
